[http]
address = "0.0.0.0:8082"
[user_mysql]
user_name="user"
password="x55NKxZMraHRXChX"
ip="10.0.2.252"
port="3306"
db_name="user"
max_conn=10
[user_redis]
ip="10.0.2.252"
port=6379
password= "123456"
db= 0
pool_size= 100